FROM node:16-alpine AS build-stage

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

ENV REACT_APP_BACKEND_URL=http://localhost:8000/api

RUN npm run build


FROM node:16-alpine

WORKDIR /app

RUN npm install -g serve && \
    adduser -D appuser

COPY --from=build-stage /app/build ./build

USER appuser

EXPOSE 5001

CMD ["serve", "-s", "-l", "5001", "build"]
