FROM node:16-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

ENV REACT_APP_BACKEND_URL=http://localhost:8000/api

RUN npm run build && \
    rm -rf src public node_modules package*.json && \
    npm cache clean --force

RUN npm install -g serve && \
    adduser -D appuser

USER appuser

EXPOSE 5001

CMD ["serve", "-s", "-l", "5001", "build"]
