FROM golang:1.16-alpine AS build-stage

WORKDIR /usr/src/app

COPY . .

ENV CGO_ENABLED=0
RUN go build -o server


FROM scratch

WORKDIR /app

ENV REQUEST_ORIGIN=http://localhost:8000

COPY --from=build-stage /usr/src/app/server ./server

USER 10001

EXPOSE 8080

CMD ["./server"]
